name: Linting

on: pull_request

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setting up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Installing dependencies
        run: yarn
      - name: Linting JS
        run: yarn lint